    window.borderDetails = [
                   { BorderType: "", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "" ,BorderType2:""},
                   { BorderType: "Right Border", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "Left Border" ,BorderType2:""},
                   {},
                   { BorderType: "Bottom Border", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "Top Border" ,BorderType2:""},
                   {},
                   { BorderType: "All Borders", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "No Border" ,BorderType2:""},
                   {},
                   { BorderType: "Outside Borders", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "Thick Box Border" ,BorderType2:""},
                   {},
                   { BorderType: "Thick Bottom Border", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "Top and Bottom Border" ,BorderType2:""},
                   {},
                   { BorderType: "Top and Thick Bottom", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "Outside Borders" ,BorderType2:""},
                   {},
                   { BorderType: "Grid Border", Border: "", Border1: "", Border2: "", Border3: "", BorderType1: "" ,BorderType2:"" },
            ];

	window.cellFormat = [
			       { name: "FONT FAMILY", style1: "Arial", style2: "Times New Roman", style3: "Tahoma", style4: "Helvetica", style5: "Calibri", style6: "Segoe UI" },
                   {},
				   { name: "FONT STYLE", style1: "Bold", style2: "Italic" },           
                   {},
				   { name: "FONT SIZE", style1: "10px", style2: "14px", style3: "16px", style4: "18px", style5: "20px" },                   
                   {},
				   { name: "FONT COLOR", style1: "Font-color", style2: "Background-color", style3: "Fore/Background" },                   
                   {},
				   { name: "TEXT DECORATION", style1: "Underline", style2: "Linethrough" },
                   {},
				   { name: "TEXT ALIGNMENT", style1: "Left", style2: "Center", style3: "Right", style4: "Justify" },                   
                   {},
				   { name: "VERTICAL ALIGNMENT", style1: "Top", style2: "Middle", style3: "Bottom", style4: "", style5: "" },
            ];
	
    window.numberFormat = [
		{ General: "Percentage", Number: "", Currency: "Number", Accounting: "", percentage: "Currency", ShortDate: "", LongDate: "Accounting", Time: "", Scientific: "General", Fraction: "", },
		{ General: "43", Number: "", Currency: "10", Accounting: "", percentage: "10", ShortDate: "", LongDate: "244", Time: "", Scientific: "Microchips", Fraction: "" },
		{ General: "23", Number: "", Currency: "9", Accounting: "", percentage: "13", ShortDate: "", LongDate: "23443", Time: "", Scientific: "Laptop", Fraction: "" },
		{ General: "45", Number: "", Currency: "15", Accounting: "", percentage: "2015", ShortDate: "", LongDate: "53454", Time: "", Scientific: "Mobile", Fraction: "" },
		{ General: "65", Number: "", Currency: "18", Accounting: "", percentage: "13", ShortDate: "", LongDate: "75656", Time: "", Scientific: "Headset", Fraction: "" },
		{ General: "", Number: "", Currency: "", Accounting: "", percentage: "", ShortDate: "", LongDate: "", Time: "", Scientific: "", Fraction: "" },
		{ General: "", Number: "", Currency: "", Accounting: "", percentage: "", ShortDate: "", LongDate: "", Time: "", Scientific: "", Fraction: "" },
		{ General: " ShortDate", Number: "", Currency: "LongDate", Accounting: "", percentage: "Time", ShortDate: "", LongDate: " Scientific", Time: "", Scientific: " Fraction", Fraction: "", },
		{ General: "12/23/2015", Number: "", Currency: "04/07/2015", Accounting: "", percentage: "10:09:15 AM", ShortDate: "", LongDate: "24562424", Time: "", Scientific: "567.456", Fraction: "" },
		{ General: "09/22/2015", Number: "", Currency: "08/04/2015", Accounting: "", percentage: "03:08:35 PM", ShortDate: "", LongDate: "24465624", Time: "", Scientific: "435.499", Fraction: "" },
		{ General: "07/16/2015", Number: "", Currency: "10/10/2015", Accounting: "", percentage: "11:11:45 PM", ShortDate: "", LongDate: "24906774", Time: "", Scientific: "245.134", Fraction: "" },
		{ General: "04/19/2015", Number: "", Currency: "11/23/2015", Accounting: "", percentage: "05:11:54 AM", ShortDate: "", LongDate: "76753453", Time: "", Scientific: "876.764", Fraction: "" },
    ];

    
    window.conditionalFormat = [
               { ItemName: "Text contains with (Loafers) apply Red Text", Date: "Loafers", Qty: "", MRP: "Date occur with 02/04/2014 in Light Red Fill with Dark Red Text", Amount: "05/03/2013", Discount: "", Netamount: "Less than 30 in Yellow Fill with Dark Yellow Text", Value: "5"},
               { ItemName: "", Date: "Casual Shoes", Qty: "", MRP: "", Amount: "06/23/2014", Discount: "", Netamount: "", Value: "56" },
               { ItemName: "", Date: "Loafers", Qty: "", MRP: "", Amount: "07/22/2014", Discount: "", Netamount: "", Value: "24" },
               { ItemName: "", Date: "Formal Shoes", Qty: "", MRP: "", Amount: "02/04/2014", Discount: "", Netamount: "", Value: "12"},
               { ItemName: "", Date: "Sandals & Floaters", Qty: "", MRP: "", Amount: "11/30/2014", Discount: "", Netamount: "", Value: "36" },
               { ItemName: "", Date: "", Qty: "", MRP: "", Amount: "", Discount: "", Netamount: "", Value: "", Value1: "", Tax:"", Tax1: "" },
               { ItemName: "Between 400 to 500 with Green Fill with Dark Green Text", Date: "273", Qty: "", MRP: "Greater Than 5000 in Light Red Fill with Dark Red Text", Amount: "5003", Discount: "", Netamount: "Equal To 20 in Red Fill", Value: "21"},
               { ItemName: "", Date: "345", Qty: "", MRP: "", Amount: "3434", Discount: "", Netamount: "", Value: "34", Value1: "" },
               { ItemName: "", Date: "494", Qty: "", MRP: "", Amount: "7553", Discount: "", Netamount: "", Value: "20", Value1: "" },
               { ItemName: "", Date: "506", Qty: "", MRP: "", Amount: "2364", Discount: "", Netamount: "", Value: "20", Value1: "" },
               { ItemName: "", Date: "453", Qty: "", MRP: "", Amount: "6788", Discount: "", Netamount: "", Value: "23", Value1: ""},
               ];

    window.visaDetail = [
			{ ID: "Greater than 6", Type: "", TypeOfVisa: "Text Length Less than 35", Value: "", VisaFees: "Between 150 to 200", FNo: "", NoOfPassenger: "List", DDate: "", Date: "Greater than 07/09/2014", DTime: "", Time: "Greaterthan 11:23:23  AM" },
			{ ID: 1, Type: "", TypeOfVisa: "Business", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "150", DDate: "", Date: "02/14/2014", DTime: "", Time: "11:34:32 AM" },
			{ ID: 2, Type: "", TypeOfVisa: "Religious Worker", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "100", DDate: "", Date: "06/11/2014", DTime: "", Time: "05:56:32 AM" },
			{ ID: 3, Type: "", TypeOfVisa: "Temporary Workers/Employment or Trainees", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "550", Date: "03/04/2012", DTime: "", Time: "07:16:22 AM" },
			{ ID: 4, Type: "", TypeOfVisa: "Transiting the United States", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "950", DDate: "", Date: "07/27/2014", DTime: "", Time: "03:32:44 AM" },
			{ ID: 5, Type: "", TypeOfVisa: "Student, Academic", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "500", DDate: "", Date: "11/21/2014", DTime: "", Time: "06:23:54 AM" },
			{ ID: 6, Type: "", TypeOfVisa: "Orphan (Intercountry Adoption)", Value: "", VisaFees: "$720.00", FNo: "", NoOfPassenger: "530", DDate: "", Date: "06/23/2014", DTime: "", Time: "11:22:59 AM" },
			{ ID: 7, Type: "", TypeOfVisa: "Exchange Visitors", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "750", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 8, Type: "", TypeOfVisa: "DV category Immigrant Visa", Value: "", VisaFees: "$360.00", FNo: "", NoOfPassenger: "950", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 9, Type: "", TypeOfVisa: "Victims of Criminal Activity", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "450", DDate: "", Date: "02/04/2014", DTime: "", Time: "03:44:34 AM" },
			{ ID: 10, Type: "", TypeOfVisa: "NAFTA Professionals", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "750", DDate: "", Date: "11/30/2014", DTime: "", Time: "03:12:52 AM" },
			{ ID: 11, Type: "", TypeOfVisa: "Employment-Based Applications", Value: "", VisaFees: "$345.00", FNo: "", NoOfPassenger: "530", DDate: "", Date: "07/09/2014", DTime: "", Time: "11:32:14 AM" },
			{ ID: 12, Type:"",TypeOfVisa: "Intracompany Transferees", Value:"",VisaFees: "$190.00", FNo:"",NoOfPassenger: "670",DDate:"",Date: "10/31/2014", DTime:"", Time: "11:01:44 AM" },
			{ ID: 13, Type: "", TypeOfVisa: "Person with Extraordinary Ability", Value: "", VisaFees: "$190.00", FNo: "", NoOfPassenger: "870", DDate: "", Date: "07/22/2014", DTime: "", Time: "10:55:53 AM" },
			{ ID: 14, Type: "", TypeOfVisa: "Tourism", Value: "", VisaFees: "$160.00", FNo: "", NoOfPassenger: "50", DDate: "", Date: "10/31/2014", DTime: "", Time: "11:01:44 AM" },
            ];

    window.chartDetails = [
                {"Company":"Edgetag","Profit":"44058.29","Country Code":"PE"},
                {"Company":"Janyx","Profit":"73956.46","Country Code":"ZM"},
                {"Company":"Trudoo","Profit":"99315.80","Country Code":"PT"},
                {"Company":"Cogibox","Profit":"62719.13","Country Code":"PT"},
                { "Company": "Camido", "Profit": "92185.71", "Country Code": "CN" },
                { "Company": "Jazzy", "Profit": "15102.06", "Country Code": "CL" },                
                { "Company": "Quatz", "Profit": "74401.61", "Country Code": "ID" },
                { "Company": "Lazzy", "Profit": "94772.16", "Country Code": "CN" },
                { "Company": "Yakidoo", "Profit": "61404.38", "Country Code": "NE" },
                { "Company": "Plambee", "Profit": "78463.09", "Country Code": "PK" },
                { "Company": "Dynazzy", "Profit": "16462.60", "Country Code": "FR" },
                { "Company": "Yombu", "Profit": "79685.65", "Country Code": "ID" },
                { "Company": "Skinder", "Profit": "19267.42", "Country Code": "KR" },                
                { "Company": "Blogtag", "Profit": "60172.96", "Country Code": "BR" },
                { "Company": "Quimba", "Profit": "23508.42", "Country Code": "FI" },
                { "Company": "Dynazzy", "Profit": "59161.32", "Country Code": "UG" },                
                { "Company": "Teklist", "Profit": "73770.79", "Country Code": "TH" },
                { "Company": "Flashset", "Profit": "13146.60", "Country Code": "PH" },
                { "Company": "Skiptube", "Profit": "86785.40", "Country Code": "CN" },
                { "Company": "Nlounge", "Profit": "84277.42", "Country Code": "SD" }
            ];

    window.employeesList = [
                {"ID":1,"Name":"Crawford","Company Name":"Camido","Country":"Indonesia","Date":"7/28/2014","Gender":"Female","Phone":"2-(426)765-2570"},
                {"ID":2,"Name":"Austin","Company Name":"Mynte","Country":"Canada","Date":"9/15/2014","Gender":"Male","Phone":"1-(778)959-2019"},
                {"ID":3,"Name":"Banks","Company Name":"Gabspot","Country":"Chile","Date":"7/31/2014","Gender":"Male","Phone":"3-(926)521-0040"},
                {"ID":4,"Name":"Stone","Company Name":"Podcat","Country":"France","Date":"6/11/2014","Gender":"Female","Phone":"8-(119)501-2358"},
                {"ID":5,"Name":"Smith","Company Name":"Gabcube","Country":"Argentina","Date":"4/18/2015","Gender":"Male","Phone":"4-(021)552-1791"},
                {"ID":6,"Name":"Montgomery","Company Name":"Avamm","Country":"Bulgaria","Date":"9/14/2014","Gender":"Female","Phone":"0-(942)837-6357"},
                {"ID":7,"Name":"Duncan","Company Name":"Kare","Country":"Colombia","Date":"8/3/2014","Gender":"Female","Phone":"9-(536)915-5018"},
                {"ID":8,"Name":"Romero","Company Name":"Voomm","Country":"China","Date":"11/10/2014","Gender":"Male","Phone":"7-(574)319-7306"},
                {"ID":9,"Name":"Lawson","Company Name":"Thoughtblab","Country":"Netherlands","Date":"7/8/2014","Gender":"Female","Phone":"2-(237)143-2948"},
                {"ID":10,"Name":"Torres","Company Name":"Rhyzio","Country":"Greece","Date":"10/5/2014","Gender":"Male","Phone":"2-(547)709-5444"},
            ];

    window.markList = [
                 { Name: "Bill", Avg: 90, Grade: "S" },
                 { Name: "John", Avg: 83, Grade: "A" },
                 { Name: "Haward", Avg: 80, Grade: "A" },
                 { Name: "Lyln", Avg: 93, Grade: "S" },
                 { Name: "Peter", Avg: 60, Grade: "D" },
                 { Name: "Lincoln", Avg: 71, Grade: "C" },
                 { Name: "David", Avg: 88, Grade: "A" },
                 { Name: "Grylls", Avg: 95, Grade: "S" },
                 { Name: "Ray", Avg: 69, Grade: "D" },
                 { Name: "Benny", Avg: 77, Grade: "C" }
             ];

    window.defaultData = [
			{ ItemName: "Casual Shoes", Date: "02/14/2014", Time: "11:34:32 AM", Qty: 10, MRP: "20", Amount: "200", Discount: "1", NetAmount: "198" },
			{ ItemName: "Sports Shoes", Date: "06/11/2014", Time: "05:56:32 AM", Qty: 20, MRP: "30", Amount: "600", Discount: "5", NetAmount: "570" },
			{ ItemName: "Formal Shoes", Date: "07/27/2014", Time: "03:32:44 AM", Qty: 20, MRP: "15", Amount: "300", Discount: "7", NetAmount: "279" },
			{ ItemName: "Sandals & Floaters", Date: "11/21/2014", Time: "06:23:54 AM", Qty: 15, MRP: "20", Amount: "300", Discount: "11", NetAmount: "267" },
			{ ItemName: "Flip- Flops & Slippers", Date: "06/23/2014", Time: "12:43:59 AM", Qty: 30, MRP: "10", Amount: "300", Discount: "10", NetAmount: "270" },
			{ ItemName: "Sneakers", Date: "07/22/2014", Time: "10:55:53 AM", Qty: 40, MRP: "20", Amount: "800", Discount: "13", NetAmount: "696" },
			{ ItemName: "Running Shoes", Date: "02/04/2014", Time: "03:44:34 AM", Qty: 20, MRP: "10", Amount: "200", Discount: "3", NetAmount: "194" },
			{ ItemName: "Loafers", Date: "11/30/2014", Time: "03:12:52 AM", Qty: 31, MRP: "10", Amount: "310", Discount: "6", NetAmount: "297" },
			{ ItemName: "Cricket Shoes", Date: "07/09/2014", Time: "11:32:14 AM", Qty: 41, MRP: "30", Amount: "1210", Discount: "12", NetAmount: "1066" },
			{ ItemName: "T-Shirts", Date: "10/31/2014", Time: "12:01:44 AM", Qty: 50, MRP: "10", Amount: "500", Discount: "9", NetAmount: "455" },
            ];
    window.eventData = [
                {"ID":1,"First_Name":"Annie","Last_Name":"Bailey","State":"Virginia","Country":"United States","Postal Code":"23605","Money":"$500.89"},
                {"ID":2,"First_Name":"Ashley","Last_Name":"Wagner","State":"West Virginia","Country":"United States","Postal Code":"25770","Money":"$629.10"},
                {"ID":3,"First_Name":"Ruth","Last_Name":"Miller","State":"New York","Country":"United States","Postal Code":"11220","Money":"$884.17"},
                {"ID":4,"First_Name":"Lois","Last_Name":"Hunt","State":"Texas","Country":"United States","Postal Code":"79950","Money":"$926.61"},
                {"ID":5,"First_Name":"Douglas","Last_Name":"Ward","State":"Virginia","Country":"United States","Postal Code":"23260","Money":"$259.87"},
                {"ID":6,"First_Name":"Billy","Last_Name":"Gomez","State":"Nevada","Country":"United States","Postal Code":"89155","Money":"$862.32"},
                {"ID":7,"First_Name":"Kathy","Last_Name":"Mason","State":"District of Columbia","Country":"United States","Postal Code":"20508","Money":"$150.41"},
                {"ID":8,"First_Name":"Roy","Last_Name":"Hall","State":"Iowa","Country":"United States","Postal Code":"51110","Money":"$403.46"},
                {"ID":9,"First_Name":"Andrea","Last_Name":"Hayes","State":"West Virginia","Country":"United States","Postal Code":"25709","Money":"$568.55"},
                {"ID":10,"First_Name":"Stephanie","Last_Name":"Tucker","State":"Connecticut","Country":"United States","Postal Code":"06905","Money":"$858.55"},
                {"ID":11,"First_Name":"Janice","Last_Name":"Bradley","State":"Minnesota","Country":"United States","Postal Code":"55166","Money":"$697.56"},
                {"ID":12,"First_Name":"Victor","Last_Name":"Ellis","State":"Wisconsin","Country":"United States","Postal Code":"53790","Money":"$303.10"},
                {"ID":13,"First_Name":"Jennifer","Last_Name":"Reid","State":"Connecticut","Country":"United States","Postal Code":"06673","Money":"$802.03"},
                {"ID":14,"First_Name":"Fred","Last_Name":"Berry","State":"Pennsylvania","Country":"United States","Postal Code":"15225","Money":"$161.49"},
                {"ID":15,"First_Name":"James","Last_Name":"Lawson","State":"Virginia","Country":"United States","Postal Code":"22205","Money":"$628.27"},
                {"ID":16,"First_Name":"Michael","Last_Name":"Johnston","State":"Oklahoma","Country":"United States","Postal Code":"73157","Money":"$411.71"},
                {"ID":17,"First_Name":"Rebecca","Last_Name":"Weaver","State":"Michigan","Country":"United States","Postal Code":"48956","Money":"$348.45"},
                {"ID":18,"First_Name":"Debra","Last_Name":"Crawford","State":"California","Country":"United States","Postal Code":"93709","Money":"$231.20"},
                {"ID":19,"First_Name":"Paula","Last_Name":"Andrews","State":"Ohio","Country":"United States","Postal Code":"43666","Money":"$116.79"},
                {"ID":20,"First_Name":"Jeremy","Last_Name":"Stanley","State":"Kansas","Country":"United States","Postal Code":"67230","Money":"$621.99"},
            ];

    window.filterData = [
                    { "Name": "Christina Wallace", "Company": "Realcube", "Country": "Ivory Coast", "Job": "Analog Circuit Design manager", "Salary": "$2826.65", "Date of Joining": "4/21/2015" },
                    { "Name": "Wayne Stone", "Company": "Tagpad", "Country": "Sweden", "Job": "Graphic Designer", "Salary": "$1543.40", "Date of Joining": "11/5/2013" },
                    { "Name": "Phyllis Cook", "Company": "Yozio", "Country": "Sweden", "Job": "Account Executive", "Salary": "$1420.71", "Date of Joining": "9/10/2013" },
                    { "Name": "Dorothy Sullivan", "Company": "Dabvine", "Country": "Indonesia", "Job": "VP Quality Control", "Salary": "$2043.23", "Date of Joining": "10/19/2013" },
                    { "Name": "Phyllis Wood", "Company": "Plajo", "Country": "United States", "Job": "Desktop Support Technician", "Salary": "$776.93", "Date of Joining": "4/23/2015" },
                    { "Name": "Susan Bishop", "Company": "Edgetag", "Country": "Philippines", "Job": "Safety Technician II", "Salary": "$1013.22", "Date of Joining": "12/16/2014" },
                    { "Name": "Elizabeth Murphy", "Company": "Gabvine", "Country": "Nigeria", "Job": "Help Desk Technician", "Salary": "$992.44", "Date of Joining": "6/5/2014" },
                    { "Name": "Lawrence Little", "Company": "Flipstorm", "Country": "Indonesia", "Job": "Electrical Engineer", "Salary": "$2970.02", "Date of Joining": "1/10/2015" },
                    { "Name": "Antonio Rose", "Company": "Livetube", "Country": "Russia", "Job": "Human Resources Manager", "Salary": "$1136.41", "Date of Joining": "3/12/2014" },
                    { "Name": "Ashley Cook", "Company": "Leenti", "Country": "Philippines", "Job": "Tax Accountant", "Salary": "$1807.98", "Date of Joining": "12/9/2013" },
                    { "Name": "Gregory Myers", "Company": "Jabberbean", "Country": "China", "Job": "Teacher", "Salary": "$1961.08", "Date of Joining": "4/4/2015" },
                    { "Name": "Eric Arnold", "Company": "Vinte", "Country": "Sweden", "Job": "Tax Accountant", "Salary": "$2236.79", "Date of Joining": "6/20/2014" },
                    { "Name": "Christine Morgan", "Company": "Avamba", "Country": "Poland", "Job": "Research Assistant I", "Salary": "$2697.58", "Date of Joining": "3/28/2015" },
                    { "Name": "William Wood", "Company": "Mymm", "Country": "Kazakhstan", "Job": "Human Resources Assistant II", "Salary": "$2564.90", "Date of Joining": "4/1/2014" },
                    { "Name": "Laura Wheeler", "Company": "Yotz", "Country": "Colombia", "Job": "General Manager", "Salary": "$2686.64", "Date of Joining": "11/18/2014" },
                    { "Name": "Julia Dunn", "Company": "Brainbox", "Country": "Uganda", "Job": "Programmer Analyst III", "Salary": "$1307.94", "Date of Joining": "7/20/2013" },
                    { "Name": "Charles Shaw", "Company": "Aimbu", "Country": "China", "Job": "Programmer I", "Salary": "$2798.29", "Date of Joining": "9/27/2014" },
                    { "Name": "Ralph Anderson", "Company": "Trunyx", "Country": "China", "Job": "Senior Financial Analyst", "Salary": "$531.04", "Date of Joining": "11/23/2014" },
                    { "Name": "Clarence Mason", "Company": "Wikizz", "Country": "China", "Job": "Marketing Assistant", "Salary": "$1097.44", "Date of Joining": "11/21/2014" },
                    { "Name": "Jimmy Alexander", "Company": "Photobug", "Country": "China", "Job": "Legal Assistant", "Salary": "$2539.84", "Date of Joining": "5/14/2014" },
                    { "Name": "Harold Perkins", "Company": "Yoveo", "Country": "Sweden", "Job": "Librarian", "Salary": "$2549.51", "Date of Joining": "2/2/2014" },
                    { "Name": "Todd Franklin", "Company": "Tagpad", "Country": "Ukraine", "Job": "Health Coach I", "Salary": "$1755.98", "Date of Joining": "1/3/2015" },
                    { "Name": "Scott Howard", "Company": "Divavu", "Country": "Colombia", "Job": "Recruiting Manager", "Salary": "$511.93", "Date of Joining": "11/16/2013" },
                    { "Name": "Amanda Fuller", "Company": "Browsedrive", "Country": "Malaysia", "Job": "Developer IV", "Salary": "$1054.88", "Date of Joining": "9/6/2013" },
                    { "Name": "Anthony Chavez", "Company": "Realbridge", "Country": "Indonesia", "Job": "Quality Engineer", "Salary": "$1516.24", "Date of Joining": "2/2/2015" },
    ];

    window.formulaData = [
                   { Function: 'String Function', Function1: '', Function2: '', Function3: 'Information Function', Function4: '', Function5: '', ItemName: 'ItemName', Qty: "Qty", MRP: 'MRP', Amount: 'Amount' },
                   { Function: '= CONCATENATE("one","big")', Function1: '', Function2: '', Function3: '=CELL("address", H2)', Function4: '', Function5: '', ItemName: 'Sports Shoes', Qty: 20, MRP: '30', Amount: '600' },
                   { Function: '=LOWER(G4)', Function1: '', Function2: '', Function3: '=ISBLANK(F2)', Function4: '', Function5: '', ItemName: 'Formal Shoes', Qty: 20, MRP: '15', Amount: '300' },
                   { Function: '=UPPER(G5)', Function1: '', Function2: '', Function3: '=ISERROR(J6)', Function4: '', Function5: '', ItemName: 'Sandals & Floaters', Qty: 15, MRP: '20', Amount: '300' },
                   { Function: '=FIND("E","SPREAD")', Function1: '', Function2: '', Function3: '=ISNUMBER(H7)', Function4: '', Function5: '', ItemName: 'Flip- Flops', Qty: 30, MRP: '10', Amount: '300' },
                   { Function: '', Function1: '', Function2: '', Function3: '=TYPE(H4)', Function4: '', Function5: '', ItemName: 'Sneakers', Qty: 40, MRP: '20', Amount: '800' },
                   { Function: '', Function1: '', Function2: '', Function3: '', Function4: '', Function5: '', ItemName: 'Running Shoes', Qty: 20, MRP: '10', Amount: '200'},
                   { Function: '', Function1: '', Function2: '', Function3: '', Function4: '', Function5: '', ItemName: 'T-Shirts', Qty: 50, MRP: '103', Amount: '3300'},
                   { Function: 'Math Function', Function1: '', Function2: '', Function3: 'Statistical and Logical', Function4: '', Function5: '', ItemName: 'Loafers', Qty: 31, MRP: '10', Amount: '310'},
                   { Function: '=SQRT(25)', Function1: '', Function2: '', Function3: '=AND(C3=5,C4=5)' , Function4: '', Function5: '', ItemName: 'Cricket Shoes', Qty: 41, MRP: '30', Amount: '1210'},
                   { Function: '=AVERAGE(J5:J9)', Function1: '', Function2: '', Function3: '=SUMIF(J4:J15, 3)', Function4: '', Function5: '', ItemName: 'T-Shirts', Qty: 50, MRP: '10', Amount: '500' },
                   { Function: '=SUM(H5:H9)', Function1: '', Function2: '', Function3: '=MAX(I4:I8)', Function4: '', Function5: '', ItemName: 'T-Shirts', Qty: 50, MRP: '10', Amount: '500' },
                   { Function: '', Function1: '', Function2: '', Function3: '=MIN(J4:J8)', Function4: '', Function5: '', ItemName: 'Running Shoes', Qty: 20, MRP: '10', Amount: '200' },

    ];

    window.freezepaneData = [
                    { "First Name": "Alan", "Last Name": "Myers", "Gender": "Male", "Designation": "Data Coordiator", "Contact No": "3-(646)378-5995" },
                    { "First Name": "Alan", "Last Name": "Garcia", "Gender": "Male", "Designation": "Chief Design Engineer", "Contact No": "5-(092)935-2805" },
                    { "First Name": "Nancy", "Last Name": "Frazier", "Gender": "Female", "Designation": "Database Administrator I", "Contact No": "9-(818)386-4240" },
                    { "First Name": "Patricia", "Last Name": "Henderson", "Gender": "Female", "Designation": "Design Engineer", "Contact No": "5-(541)628-7226" },
                    { "First Name": "Angela", "Last Name": "Carroll", "Gender": "Female", "Designation": "Marketing Assistant", "Contact No": "4-(164)971-8000" },
                    { "First Name": "Thomas", "Last Name": "Lewis", "Gender": "Male", "Designation": "Director of Sales", "Contact No": "8-(603)314-5777" },
                    { "First Name": "Thomas", "Last Name": "Bell", "Gender": "Male", "Designation": "Nurse Practicioner", "Contact No": "4-(069)832-8815" },
                    { "First Name": "Adam", "Last Name": "Andrews", "Gender": "Male", "Designation": "Help Desk Operator", "Contact No": "4-(072)290-1316" },
                    { "First Name": "Joe", "Last Name": "Owens", "Gender": "Male", "Designation": "Associate Professor", "Contact No": "4-(922)789-9434" },
                    { "First Name": "Terry", "Last Name": "Lawrence", "Gender": "Male", "Designation": "Software Engineer I", "Contact No": "3-(277)391-0992" },
                    { "First Name": "Joe", "Last Name": "James", "Gender": "Male", "Designation": "VP Sales", "Contact No": "6-(763)551-5257" },
                    { "First Name": "Jesse", "Last Name": "Adams", "Gender": "Male", "Designation": "General Manager", "Contact No": "9-(894)772-8815" },
                    { "First Name": "Raymond", "Last Name": "Carr", "Gender": "Male", "Designation": "Occupational Therapist", "Contact No": "9-(779)917-6534" },
                    { "First Name": "Dennis", "Last Name": "Shaw", "Gender": "Male", "Designation": "Editor", "Contact No": "9-(350)703-6816" },
                    { "First Name": "Diana", "Last Name": "Scott", "Gender": "Female", "Designation": "Director of Sales", "Contact No": "9-(501)466-5381" },
                    { "First Name": "Kelly", "Last Name": "Gibson", "Gender": "Female", "Designation": "Developer I", "Contact No": "6-(922)641-8366" },
                    { "First Name": "Sharon", "Last Name": "Ellis", "Gender": "Female", "Designation": "Editor", "Contact No": "9-(420)864-5535" },
                    { "First Name": "Stephen", "Last Name": "Hunter", "Gender": "Male", "Designation": "Geologist III", "Contact No": "9-(756)680-8555" },
                    { "First Name": "Shawn", "Last Name": "Henry", "Gender": "Male", "Designation": "Senior Financial Analyst", "Contact No": "4-(581)957-4967" },
                    { "First Name": "Antonio", "Last Name": "Perry", "Gender": "Male", "Designation": "VP Accounting", "Contact No": "2-(263)696-6272" }
    ];

    window.hyperlinkData = [
				{ ItemName: "Casual Shoes", Qty: 10, MRP: "$20", Amount: "$200",StockDetail:"OUT OF STOCK","Website":"Amazon"},
				{ ItemName: "Sports Shoes", Qty: 20, MRP: "$30", Amount: "$600", StockDetail: "IN STOCK", "Website": "" },
				{ ItemName: "Formal Shoes", Qty: 20, MRP: "$15", Amount: "$300", StockDetail: "IN STOCK", "Website": "AliExpress" },
				{ ItemName: "Sandals & Floaters", Qty: 15, MRP: "$20", Amount: "$300", StockDetail: "OUT OF STOCK", "Website": "AliBaba" },
				{ ItemName: "Flip-Flops & Slippers", Qty: 30, MRP: "$10", Amount: "$300", StockDetail: "IN STOCK", "Website": "" },
				{ ItemName: "Sneakers", Qty: 40, MRP: "$20", Amount: "$800", StockDetail: "OUT OF STOCK", "Website": "" },
				{ ItemName: "Running Shoes", Qty: 20, MRP: "$10", Amount: "$200", StockDetail: "IN STOCK", "Website": "Ebay" },
				{ ItemName: "Loafers", Qty: 31, MRP: "$10", Amount: "$310", StockDetail: "IN STOCK", "Website": "" },
				{ ItemName: "Cricket Shoes", Qty: 41, MRP: "$30", Amount: "$1210", StockDetail: "IN STOCK", "Website": "" },
				{ ItemName: "T-Shirts", Qty: 50, MRP: "$10", Amount: "$500", StockDetail: "IN STOCK", "Website": "" },
    ];

    window.importData = [
              { "ITEM CODE": 23466, "DESCRIPTION": "Common Brick Masonry", "WORK UNIT": 1000, "LABOUR CODE": "W-431", "TIME UNIT": "Shift", "MATL UNIT COST": 1240, "INSTCOST": 257 },
              { "ITEM CODE": 23456, "DESCRIPTION": "Stone Masonry", "WORK UNIT": 500, "LABOUR CODE": "W-417", "TIME UNIT": "Regular", "MATL UNIT COST": 3400, "INSTCOST": 655 },
              { "ITEM CODE": 23436, "DESCRIPTION": "Rubble Masonry", "WORK UNIT": 750, "LABOUR CODE": "W-402", "TIME UNIT": "Shift", "MATL UNIT COST": 4500, "INSTCOST": 545 },
              { "ITEM CODE": 23426, "DESCRIPTION": "Ashlar Masonry", "WORK UNIT": 300, "LABOUR CODE": "W-325", "TIME UNIT": "Shift", "MATL UNIT COST": 6500, "INSTCOST": 650 },
              { "ITEM CODE": 23416, "DESCRIPTION": "Stone Masonry", "WORK UNIT": 700, "LABOUR CODE": "W-398", "TIME UNIT": "Regular", "MATL UNIT COST": 7500, "INSTCOST": 650 },
              { "ITEM CODE": 23475, "DESCRIPTION": "Stone Masonry", "WORK UNIT": 450, "LABOUR CODE": "W-765", "TIME UNIT": "Regular", "MATL UNIT COST": 8000, "INSTCOST": 450 },
              { "ITEM CODE": 23486, "DESCRIPTION": "Common Brick Masonry", "WORK UNIT": 400, "LABOUR CODE": "W-875", "TIME UNIT": "Shift", "MATL UNIT COST": 2245, "INSTCOST": 600 },
              { "ITEM CODE": 23418, "DESCRIPTION": "Rubble Masonry", "WORK UNIT": 200, "LABOUR CODE": "W-456", "TIME UNIT": "Regular", "MATL UNIT COST": 5430, "INSTCOST": 350 },
              { "ITEM CODE": 23494, "DESCRIPTION": "Ashlar Masonry", "WORK UNIT": 300, "LABOUR CODE": "W-234", "TIME UNIT": "Shift", "MATL UNIT COST": 3350, "INSTCOST": 370 },
              { "ITEM CODE": 24410, "DESCRIPTION": "Rubble Masonry", "WORK UNIT": 600, "LABOUR CODE": "W-635", "TIME UNIT": "Regular", "MATL UNIT COST": 2500, "INSTCOST": 430 }
    ];

    window.localizeData = [
            { "firstname": "First Name", "lastname": "Last Name", "username": "User Name", "jobtitle": "Job Title", "email": "Email", "country": "Country" },
    { "firstname": "Joe", "lastname": "Fisher", "username": "jfisher1g", "jobtitle": "Research Nurse", "email": "jfisher1g@census.gov", "country": "Ukraine" },
    { "firstname": "Donna", "lastname": "Lane", "username": "dlane1h", "jobtitle": "Occupational Therapist", "email": "dlane1h@ucoz.ru", "country": "Morocco" },
    { "firstname": "Kathleen", "lastname": "Green", "username": "kgreen1i", "jobtitle": "Geologist III", "email": "kgreen1i@usda.gov", "country": "Brazil" },
    { "firstname": "Russell", "lastname": "Fowler", "username": "rfowler1j", "jobtitle": "Programmer Analyst II", "email": "rfowler1j@google.com.br", "country": "Poland" },
    { "firstname": "Jane", "lastname": "Burns", "username": "jburns1k", "jobtitle": "Budget/Accounting Analyst III", "email": "jburns1k@eepurl.com", "country": "China" },
    { "firstname": "Jane", "lastname": "Lopez", "username": "jlopez1l", "jobtitle": "Quality Control Specialist", "email": "jlopez1l@yahoo.co.jp", "country": "Argentina" },
    { "firstname": "Rachel", "lastname": "Ray", "username": "rray1m", "jobtitle": "Project Manager", "email": "rray1m@1und1.de", "country": "China" },
    { "firstname": "William", "lastname": "Gomez", "username": "wgomez1n", "jobtitle": "Associate Professor", "email": "wgomez1n@adobe.com", "country": "Poland" },
    { "firstname": "Stephen", "lastname": "Reyes", "username": "sreyes1o", "jobtitle": "Professor", "email": "sreyes1o@seesaa.net", "country": "Czech Republic" },
    { "firstname": "Gary", "lastname": "Lawson", "username": "glawson1p", "jobtitle": "Account Representative IV", "email": "glawson1p@live.com", "country": "Sweden" },
    { "firstname": "Jose", "lastname": "Wheeler", "username": "jwheeler1q", "jobtitle": "Community Outreach Specialist", "email": "jwheeler1q@cafepress.com", "country": "Malta" },
    { "firstname": "Eric", "lastname": "Ferguson", "username": "eferguson1r", "jobtitle": "Senior Sales Associate", "email": "eferguson1r@istockphoto.com", "country": "Russia" },
    { "firstname": "Patrick", "lastname": "Reed", "username": "preed1s", "jobtitle": "Programmer III", "email": "preed1s@theglobeandmail.com", "country": "Egypt" },
    { "firstname": "Harry", "lastname": "Edwards", "username": "hedwards1t", "jobtitle": "Automation Specialist IV", "email": "hedwards1t@utexas.edu", "country": "Sweden" },
    { "firstname": "Tammy", "lastname": "West", "username": "twest1u", "jobtitle": "Software Engineer IV", "email": "twest1u@ucoz.com", "country": "Tajikistan" },
    { "firstname": "Marie", "lastname": "Turner", "username": "mturner1v", "jobtitle": "Data Coordiator", "email": "mturner1v@bluehost.com", "country": "Russia" },
    { "firstname": "Joseph", "lastname": "Chavez", "username": "jchavez1w", "jobtitle": "Web Designer IV", "email": "jchavez1w@g.co", "country": "China" },
    { "firstname": "Jimmy", "lastname": "Mills", "username": "jmills1x", "jobtitle": "Graphic Designer", "email": "jmills1x@symantec.com", "country": "Georgia" },
    { "firstname": "Albert", "lastname": "Olson", "username": "aolson1y", "jobtitle": "VP Marketing", "email": "aolson1y@soup.io", "country": "Tanzania" },
    { "firstname": "Jimmy", "lastname": "Jordan", "username": "jjordan1z", "jobtitle": "Dental Hygienist", "email": "jjordan1z@opensource.org", "country": "Philippines" },
    { "firstname": "Anne", "lastname": "Gonzales", "username": "agonzales20", "jobtitle": "Nuclear Power Engineer", "email": "agonzales20@google.com.hk", "country": "Poland" },
    { "firstname": "Adam", "lastname": "Nichols", "username": "anichols21", "jobtitle": "Accountant III", "email": "anichols21@mozilla.com", "country": "Netherlands" },
    { "firstname": "Shirley", "lastname": "Cox", "username": "scox22", "jobtitle": "Engineer I", "email": "scox22@macromedia.com", "country": "Comoros" },
    { "firstname": "Gerald", "lastname": "Diaz", "username": "gdiaz23", "jobtitle": "Legal Assistant", "email": "gdiaz23@angelfire.com", "country": "France" },
    { "firstname": "Frank", "lastname": "Carter", "username": "fcarter24", "jobtitle": "Web Designer I", "email": "fcarter24@home.pl", "country": "Argentina" },
    ];

    window.mergeData = [
                { "BookName": "BookName", "AuthorName": "AuthorName", "Buying Price": "PriceDetail", "Selling Price": "", "Profit": "Profit(%)", "Buying Date": "Buying Date" },
                {  "BookName": "", "AuthorName": "", "Buying Price": "Buying Price", "Selling Price": "Selling Price", "Profit":"","Buying Date": "" },
                {  "BookName": "All the King's Men", "AuthorName": "Robert Penn Warren", "Buying Price": 25, "Selling Price": 27, "Profit":12,"Buying Date": "7/28/2014" },
                { "BookName": "Amar Kosh", "AuthorName": "Amar Singh", "Buying Price": 35, "Selling Price": 36, "Profit": 7, "Buying Date": "7/28/2014" },
                {  "BookName": "American Capitalism", "AuthorName": "J.K. Galbraith", "Buying Price": 22, "Selling Price": 26, "Profit":13,"Buying Date": "02/18/2014" },
                {  "BookName": "Ambassador's Journal", "AuthorName": "J.K. Galbraith", "Buying Price": 19, "Selling Price": 22, "Profit":12,"Buying Date": "03/21/2014" },
                {  "BookName": "Affluent Society", "AuthorName": "J.K. Galbraith", "Buying Price": 26, "Selling Price": 27, "Profit":5,"Buying Date": "07/15/2014" },
                {  "BookName": "Arms and the Man", "AuthorName": "G.B.Shaw", "Buying Price": 31, "Selling Price": 32, "Profit": 4, "Buying Date": "03/12/2014" },
                {  "BookName": "Treasure Island", "AuthorName": "R.L.Stevenson", "Buying Price": 20, "Selling Price": 25, "Profit": 22, "Buying Date": "03/12/2014" },
                {  "BookName": "Adventures of Huckleberry Finn", "AuthorName": "Mark Twain", "Buying Price": 23, "Selling Price": 24, "Profit":7,"Buying Date": "12/24/2014" },
                { "BookName": "Adventures of Tom Sawyer", "AuthorName": "Mark Twain", "Buying Price": 31, "Selling Price": 34, "Profit": 12, "Buying Date": "10/31/2014" },
                 { "BookName": "", "AuthorName": "", "Buying Price":"", "Selling Price":"", "Profit":"", "Buying Date": "" },
                { "BookName": "Total", "AuthorName": "", "Buying Price":212, "Selling Price":233, "Profit": 9, "Buying Date": "" },
            ];

    window.moviesList = [
                    { no: "NO", year: "YEAR", title: "TITLE", review: "REVIEW", actors: "STARRING ACTORS", director: "DIRECTOR", genre: "GENRE", rating: "RATING", format: "FORMAT", comments: "COMMENTS" },
                    { "no": 1, "year": 1994, "title": "Forrest Gump", "review": "5 Stars", "actors": "Tom Hanks, Robin Wright, Gary Sinise", "director": "Robert Zemeckis", "genre": "Drama", "rating": "PG-13", "format": "DVD", "comments": "Based on the 1986 novel of the same name by Winston Groom" },
                    { "no": 2, "year": 1946, "title": "It’s a Wonderful Life", "review": "2 Stars", "actors": "James Stewart, Donna Reed, Lionel Barrymore ", "director": "Frank Capra", "genre": "Drama", "rating": "G", "format": "VHS", "comments": "Colorized version" },
                    { "no": 3, "year": 1988, "title": "Big", "review": "4 Stars", "actors": "Tom Hanks, Elizabeth Perkins, Robert Loggia ", "director": "Penny Marshall", "genre": "Comedy", "rating": "PG", "format": "DVD", "comments": "" },
                    { "no": 4, "year": 1954, "title": "Rear Window", "review": "3 Stars", "actors": "James Stewart, Grace Kelly, Wendell Corey ", "director": "Alfred Hitchcock", "genre": "Suspense", "rating": "PG", "format": "Blu-ray", "comments": "" },
    ];

    window.fifaWinnerList = [
                     { Rank: "1", Team: "Germany", Points: "1725", WorldCup: "4 times", Years: "1954, 1974, 1990, 2014", RunnerUp: "4 times" },
                     { Rank: "2", Team: "Argentina", Points: "1538", WorldCup: "2 times", Years: "1978, 1986", RunnerUp: "3 times" },
                     { Rank: "3", Team: "Colombia", Points: "1450", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "4", Team: "Belgium", Points: "1417", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "5", Team: "Netherlands", Points: "1374", WorldCup: "NO", Years: "NO", RunnerUp: "3 times" },
                     { Rank: "6", Team: "Brazil", Points: "1316", WorldCup: "5 times", Years: "1958, 1962, 1970, 1994, 2002", RunnerUp: "2 times" },
                     { Rank: "7", Team: "Portugal", Points: "1160", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "7", Team: "France", Points: "1160", WorldCup: "1 time", Years: "1998", RunnerUp: "1 time" },
                     { Rank: "9", Team: "Spain", Points: "1142", WorldCup: "1 time", Years: "2010", RunnerUp: "NO" },
                     { Rank: "10", Team: "Uruguay", Points: "1135", WorldCup: "2 times", Years: "1930, 1950", RunnerUp: "2 times" },
                     { Rank: "11", Team: "Italy", Points: "1103", WorldCup: "4 times", Years: "1934, 1938, 1982, 2006", RunnerUp: "NO" },
                     { Rank: "12", Team: "Switzerland", Points: "1091", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "13", Team: "England", Points: "1032", WorldCup: "1 time", Years: "1966", RunnerUp: "NO" },
                     { Rank: "14", Team: "Chile", Points: "1022", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "15", Team: "Romania", Points: "1014", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "16", Team: "Costa Rica", Points: "995", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "17", Team: "Czech Republic", Points: "987", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "18", Team: "Algeria", Points: "948", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "19", Team: "Croatia", Points: "946", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
                     { Rank: "20", Team: "Mexico", Points: "913", WorldCup: "NO", Years: "NO", RunnerUp: "NO" },
    ];

    window.companyList = [
                    { "Company ": "Skimia", "Manager": "Evelyn Coleman", "Address": "888 Lunder Road", "E-mail": "ecoleman0@xrea.com", "City": "Pensacola", "State": "Florida", "Country": "United States", "Postal Code": "32575" },
                    { "Company ": "Rhycero", "Manager": "Martha Lawson", "Address": "0 Esch Avenue", "E-mail": "mlawson1@quantcast.com", "City": "Lincoln", "State": "Nebraska", "Country": "United States", "Postal Code": "68531" },
                    { "Company ": "Fiveclub", "Manager": "Ryan Lee", "Address": "0696 West Road", "E-mail": "rlee2@deviantart.com", "City": "San Antonio", "State": "Texas", "Country": "United States", "Postal Code": "78245" },
                    { "Company ": "Edgeclub", "Manager": "Henry Moore", "Address": "45 Monterey Court", "E-mail": "hmoore3@yahoo.com", "City": "Henderson", "State": "Nevada", "Country": "United States", "Postal Code": "89012" },
                    { "Company ": "Yakijo", "Manager": "Ruth Duncan", "Address": "56 Spenser Place", "E-mail": "rduncan4@nbcnews.com", "City": "Louisville", "State": "Kentucky", "Country": "United States", "Postal Code": "40298" },
                    { "Company ": "Twinte", "Manager": "Alice Gardner", "Address": "517 Dawn Road", "E-mail": "agardner5@tinypic.com", "City": "Reno", "State": "Nevada", "Country": "United States", "Postal Code": "89595" },
                    { "Company ": "Leenti", "Manager": "Albert Carr", "Address": "26271 Miller Terrace", "E-mail": "acarr6@merriam-webster.com", "City": "New Orleans", "State": "Louisiana", "Country": "United States", "Postal Code": "70116" },
                    { "Company ": "Wikivu", "Manager": "Henry Reyes", "Address": "4263 Union Parkway", "E-mail": "hreyes7@reddit.com", "City": "Flint", "State": "Michigan", "Country": "United States", "Postal Code": "48505" },
                    { "Company ": "Oyope", "Manager": "Anne Warren", "Address": "428 Hoffman Trail", "E-mail": "awarren8@geocities.com", "City": "Jackson", "State": "Mississippi", "Country": "United States", "Postal Code": "39210" },
                    { "Company ": "Jaxnation", "Manager": "Carl Robertson", "Address": "3 Johnson Road", "E-mail": "crobertson9@wikimedia.org", "City": "Valley Forge", "State": "Pennsylvania", "Country": "United States", "Postal Code": "19495" },
                    { "Company ": "Innotype", "Manager": "Dennis Greene", "Address": "03 Glacier Hill Way", "E-mail": "dgreenea@shinystat.com", "City": "Virginia Beach", "State": "Virginia", "Country": "United States", "Postal Code": "23464" },
                    { "Company ": "Topiclounge", "Manager": "Gerald Black", "Address": "8 Jenifer Terrace", "E-mail": "gblackb@csmonitor.com", "City": "Fredericksburg", "State": "Virginia", "Country": "United States", "Postal Code": "22405" },
                    { "Company ": "Avaveo", "Manager": "Marilyn Perez", "Address": "040 Sherman Avenue", "E-mail": "mperezc@telegraph.co.uk", "City": "Rochester", "State": "New York", "Country": "United States", "Postal Code": "14609" },
                    { "Company ": "Gabtune", "Manager": "Harry Stewart", "Address": "6 Calypso Terrace", "E-mail": "hstewartd@bravesites.com", "City": "Dayton", "State": "Ohio", "Country": "United States", "Postal Code": "45403" },
                    { "Company ": "Innojam", "Manager": "Jennifer Stewart", "Address": "23411 Brown Drive", "E-mail": "jstewarte@wsj.com", "City": "Canton", "State": "Ohio", "Country": "United States", "Postal Code": "44760" },
                    { "Company ": "Wikizz", "Manager": "Gerald Bell", "Address": "072 Sommers Park", "E-mail": "gbellf@time.com", "City": "Kansas City", "State": "Missouri", "Country": "United States", "Postal Code": "64153" },
                    { "Company ": "Mybuzz", "Manager": "Steven Ross", "Address": "30 Scoville Parkway", "E-mail": "srossg@ebay.co.uk", "City": "Miami", "State": "Florida", "Country": "United States", "Postal Code": "33169" },
                    { "Company ": "Innojam", "Manager": "Philip Simpson", "Address": "26608 Monterey Drive", "E-mail": "psimpsonh@devhub.com", "City": "Canton", "State": "Ohio", "Country": "United States", "Postal Code": "44720" },
                    { "Company ": "Mudo", "Manager": "Heather Carr", "Address": "97609 Prairie Rose Lane", "E-mail": "hcarri@pen.io", "City": "Roanoke", "State": "Virginia", "Country": "United States", "Postal Code": "24048" },
                    { "Company ": "Kwimbee", "Manager": "Anne Daniels", "Address": "582 Talisman Street", "E-mail": "adanielsj@nsw.gov.au", "City": "Atlanta", "State": "Georgia", "Country": "United States", "Postal Code": "31136" },
                    { "Company ": "Teklist", "Manager": "Frances Harper", "Address": "6013 Luster Crossing", "E-mail": "fharperk@sbwire.com", "City": "Columbus", "State": "Ohio", "Country": "United States", "Postal Code": "43215" },
                    { "Company ": "Rooxo", "Manager": "Dennis Mendoza", "Address": "43 Northfield Circle", "E-mail": "dmendozal@nsw.gov.au", "City": "Philadelphia", "State": "Pennsylvania", "Country": "United States", "Postal Code": "19146" },
                    { "Company ": "Viva", "Manager": "Linda Davis", "Address": "39 Hallows Plaza", "E-mail": "ldavism@stumbleupon.com", "City": "Oklahoma City", "State": "Oklahoma", "Country": "United States", "Postal Code": "73173" },
                    { "Company ": "Gabspot", "Manager": "Judith Torres", "Address": "24554 Derek Terrace", "E-mail": "jtorresn@webeden.co.uk", "City": "Dallas", "State": "Texas", "Country": "United States", "Postal Code": "75221" },
                    { "Company ": "Tazz", "Manager": "Katherine Jordan", "Address": "3536 Meadow Vale Lane", "E-mail": "kjordano@liveinternet.ru", "City": "Fort Myers", "State": "Florida", "Country": "United States", "Postal Code": "33913" },
                    { "Company ": "Layo", "Manager": "Nancy Bryant", "Address": "8946 Cambridge Terrace", "E-mail": "nbryantp@weibo.com", "City": "Detroit", "State": "Michigan", "Country": "United States", "Postal Code": "48206" },
                    { "Company ": "Vitz", "Manager": "Clarence Bell", "Address": "0121 Armistice Terrace", "E-mail": "cbellq@earthlink.net", "City": "Cedar Rapids", "State": "Iowa", "Country": "United States", "Postal Code": "52410" },
                    { "Company ": "Flashspan", "Manager": "Billy Gordon", "Address": "83 Melby Court", "E-mail": "bgordonr@dell.com", "City": "Oklahoma City", "State": "Oklahoma", "Country": "United States", "Postal Code": "73129" },
                    { "Company ": "Skiba", "Manager": "Alice Edwards", "Address": "3558 Pleasure Park", "E-mail": "aedwardss@purevolume.com", "City": "Minneapolis", "State": "Minnesota", "Country": "United States", "Postal Code": "55407" },
                    { "Company ": "Quamba", "Manager": "Alan Shaw", "Address": "28 Reindahl Lane", "E-mail": "ashawt@ted.com", "City": "New York City", "State": "New York", "Country": "United States", "Postal Code": "10165" },
                    { "Company ": "Oodoo", "Address": "Armstrong", "Manager": "Andrew Armstrong", "E-Mail": "aarmstrong0@timesonline.co.uk", "City": "Tuusula", "State": "14.130.161.222", "Country": "Finland" },
                    { "Company ": "Bubbletube", "Address": "Palmer", "Manager": "Patrick Palmer", "E-Mail": "ppalmer1@istockphoto.com", "City": "Kadupinang", "State": "58.114.186.254", "Country": "Indonesia" },
                    { "Company ": "Twinder", "Address": "Martinez", "Manager": "Roger Martinez", "E-Mail": "rmartinez2@yolasite.com", "City": "Diancun", "State": "174.172.164.126", "Country": "China" },
                    { "Company ": "Pixoboo", "Address": "Bradley", "Manager": "Victor Bradley", "E-Mail": "vbradley3@ibm.com", "City": "Guamo", "State": "190.226.18.92", "Country": "Colombia" },
                    { "Company ": "Yozio", "Address": "Ford", "Manager": "Louise Ford", "E-Mail": "lford4@aol.com", "City": "Kaz", "State": "160.156.252.69", "Country": "Russia" },
                    { "Company ": "Talane", "Address": "Ortiz", "Manager": "Barbara Ortiz", "E-Mail": "bortiz5@goo.ne.jp", "City": "Kushnytsya", "State": "224.72.68.37", "Country": "Ukraine" },
                    { "Company ": "Tazzy", "Address": "Gray", "Manager": "Tina Gray", "E-Mail": "tgray6@imgur.com", "City": "Gunjur", "State": "235.196.232.208", "Country": "Gambia" },
                    { "Company ": "Browsetype", "Address": "Morrison", "Manager": "Mark Morrison", "E-Mail": "mmorrison7@reverbnation.com", "City": "Täby", "State": "253.231.20.204", "Country": "Sweden", "Postal Code": "183 83" },
                    { "Company ": "Skibox", "Address": "Schmidt", "Manager": "Frank Schmidt", "E-Mail": "fschmidt8@chronoengine.com", "City": "Zarya", "State": "176.244.148.174", "Country": "Ukraine" },
                    { "Company ": "Innotype", "Address": "Nichols", "Manager": "John Nichols", "E-Mail": "jnichols9@php.net", "City": "Spring", "State": "140.139.167.197", "Country": "United States", "Postal Code": "77386" },
                    { "Company ": "Plambee", "Address": "Peters", "Manager": "Lillian Peters", "E-Mail": "lpetersa@nymag.com", "City": "Jistebnice", "State": "163.127.7.170", "Country": "Czech Republic" },
                    { "Company ": "Meemm", "Address": "Dunn", "Manager": "Clarence Dunn", "E-Mail": "cdunnb@themeforest.net", "City": "Telheira", "State": "252.94.131.84", "Country": "Portugal", "Postal Code": "4650-669" },
                    { "Company ": "Aivee", "Address": "Morgan", "Manager": "Donna Morgan", "E-Mail": "dmorganc@ox.ac.uk", "City": "Yixing", "State": "164.89.222.36", "Country": "China" },
                    { "Company ": "Livetube", "Address": "Martin", "Manager": "Robin Martin", "E-Mail": "rmartind@123-reg.co.uk", "City": "Secunda", "State": "186.167.83.172", "Country": "South Africa" },
                    { "Company ": "Thoughtbridge", "Address": "Perez", "Manager": "Michelle Perez", "E-Mail": "mpereze@japanpost.jp", "City": "Dioila", "State": "246.188.160.117", "Country": "Mali" },
                    { "Company ": "Rhynoodle", "Address": "Gibson", "Manager": "Marilyn Gibson", "E-Mail": "mgibsonf@blog.com", "City": "Huangjinbu", "State": "126.198.57.253", "Country": "China" },
                    { "Company ": "Kwilith", "Address": "Walker", "Manager": "Jesse Walker", "E-Mail": "jwalkerg@tripod.com", "City": "Cibanten", "State": "191.220.49.67", "Country": "Indonesia" }
    ];

    window.personList = [
                { "Name": "Sean", "Language": "Greek", "Country": "Peru", "E-mail": "sedwards0@cdc.gov", "Contact No": "3-(957)983-8117" },
                { "Name": "Angela", "Language": "Kyrgyz", "Country": "Brazil", "E-mail": "aortiz1@miibeian.gov.cn", "Contact No": "1-(735)580-2105" },
                { "Name": "Jack", "Language": "Estonian", "Country": "Poland", "E-mail": "jshaw2@twitter.com", "Contact No": "0-(462)409-3196" },
                { "Name": "Larry", "Language": "Estonian", "Country": "Poland", "E-mail": "lwoods3@nytimes.com", "Contact No": "4-(482)081-6926" },
                { "Name": "Sara", "Language": "Norwegian", "Country": "China", "E-mail": "sandrews4@nature.com", "Contact No": "3-(568)870-1792" },
                { "Name": "Jerry", "Language": "Czech", "Country": "China", "E-mail": "jfox5@hhs.gov", "Contact No": "3-(433)588-5242" },
                { "Name": "Brian", "Language": "Latvian", "Country": "China", "E-mail": "bmorrison6@topsy.com", "Contact No": "8-(934)486-9711" },
                { "Name": "Harold", "Language": "Hungarian", "Country": "China", "E-mail": "hwilliamson7@hugedomains.com", "Contact No": "7-(826)742-9984" },
                { "Name": "Andrea", "Language": "French", "Country": "Afghanistan", "E-mail": "acruz8@posterous.com", "Contact No": "2-(102)383-7249" },
                { "Name": "Jean", "Language": "Hungarian", "Country": "Portugal", "E-mail": "jberry9@dedecms.com", "Contact No": "5-(322)674-1411" },
                { "Name": "Joe", "Language": "Estonian", "Country": "United States", "E-mail": "jpaynea@ebay.com", "Contact No": "3-(182)011-7204" },
                { "Name": "Judith", "Language": "Italian", "Country": "Indonesia", "E-mail": "jhansenb@seattletimes.com", "Contact No": "7-(058)651-0678" },
                { "Name": "Raymond", "Language": "Kyrgyz", "Country": "China", "E-mail": "rreyesc@ow.ly", "Contact No": "8-(611)319-3603" },
                { "Name": "Robert", "Language": "Czech", "Country": "Democratic Republic of the Congo", "E-mail": "rkelleyd@geocities.com", "Contact No": "9-(837)456-7906" },
                { "Name": "Susan", "Language": "Dzongkha", "Country": "United States", "E-mail": "sharrisone@4shared.com", "Contact No": "6-(908)827-9046" },
                { "Name": "Jimmy", "Language": "Albanian", "Country": "Cyprus", "E-mail": "jweaverf@google.ru", "Contact No": "4-(003)706-0340" },
                { "Name": "Mildred", "Language": "Kurdish", "Country": "Indonesia", "E-mail": "mreidg@123-reg.co.uk", "Contact No": "1-(846)697-6636" },
                { "Name": "Albert", "Language": "Bulgarian", "Country": "Indonesia", "E-mail": "acookh@dagondesign.com", "Contact No": "5-(068)124-0912" },
                { "Name": "Brenda", "Language": "Maltese", "Country": "Portugal", "E-mail": "bgriffini@aol.com", "Contact No": "6-(333)150-5361" },
                { "Name": "Cynthia", "Language": "Gujarati", "Country": "Czech Republic", "E-mail": "cparkerj@goo.gl", "Contact No": "7-(667)497-7917" }
    ];

    window.stockList = [
                    { "SNo": 1, "Name": "Margaret Ramirez", "Country": "Portugal", "Date": "1/30/2015", "Currency": "Euro", "Money": "6.34", "Time": "7:35:23 PM" },
                    { "SNo": 2, "Name": "Dennis Griffin", "Country": "South Africa", "Date": "10/17/2014", "Currency": "Rand", "Money": "0.14", "Time": "8:34:34 PM" },
                    { "SNo": 3, "Name": "Lori West", "Country": "Finland", "Date": "10/23/2014", "Currency": "Euro", "Money": "3.78", "Time": "12:45:43 AM" },
                    { "SNo": 4, "Name": "Eugene Mason", "Country": "Canada", "Date": "8/14/2014", "Currency": "Dollar", "Money": "2.64", "Time": "12:05:23 PM" },
                    { "SNo": 5, "Name": "Justin Crawford", "Country": "Russia", "Date": "12/14/2014", "Currency": "Ruble", "Money": "4.81", "Time": "4:18:56 AM" },
                    { "SNo": 6, "Name": "Sharon Perez", "Country": "Indonesia", "Date": "3/10/2015", "Currency": "Rupiah", "Money": "8.73", "Time": "9:50:32 PM" },
                    { "SNo": 7, "Name": "Alice Hart", "Country": "Botswana", "Date": "10/3/2014", "Currency": "Pula", "Money": "3.68", "Time": "7:54:23 PM" },
                    { "SNo": 8, "Name": "Laura Walker", "Country": "Lesotho", "Date": "12/22/2014", "Currency": "Loti", "Money": "0.83", "Time": "3:45:09 PM" },
                    { "SNo": 9, "Name": "Shirley Mills", "Country": "China", "Date": "7/8/2014", "Currency": "Yuan Renminbi", "Money": "9.36", "Time": "11:04:56 PM" },
                    { "SNo": 10, "Name": "Henry Romero", "Country": "Poland", "Date": "3/26/2015", "Currency": "Zloty", "Money": "2.52", "Time": "3:03:03 PM" },
                    { "SNo": 11, "Name": "Roger Scott", "Country": "Nicaragua", "Date": "9/10/2014", "Currency": "Cordoba", "Money": "9.67", "Time": "8:08:08 AM" },
                    { "SNo": 12, "Name": "Stephen Griffin", "Country": "Indonesia", "Date": "9/15/2014", "Currency": "Rupiah", "Money": "1.38", "Time": "4:48:48 PM" },
                    { "SNo": 13, "Name": "Sharon Chavez", "Country": "Ukraine", "Date": "7/9/2014", "Currency": "Hryvnia", "Money": "6.06", "Time": "4:22:43 AM" },
                    { "SNo": 14, "Name": "Sandra Williams", "Country": "Portugal", "Date": "7/3/2014", "Currency": "Euro", "Money": "8.34", "Time": "7:24:24 PM" }
    ];

    window.bill = [
              { ItemName: "ItemName", Qty: "Qty", Stock: "", MRP: "ItemName", Amount: "Qty", Discount: "", Total: "ItemName", NetAmount: "Qty" },
              { ItemName: "Casual Shoes", Qty: 10, Stock: "", MRP: "Sandals & Floaters", Amount: 200, Discount: "", Total: "Running Shoes", NetAmount: 198 },
              { ItemName: "Sports Shoes", Qty: 20, Stock: "", MRP: "Flip- Flops", Amount: 600, Discount: "", Total: "Loafers", NetAmount: 570 },
              { ItemName: "Formal Shoes", Qty: 20, Stock: "", MRP: "Sneakers", Amount: 300, Discount: "", Total: "T-Shirts", NetAmount: 279 },
              { ItemName: " ", Qty: " ", Stock: "", MRP: " ", Amount: " ", Discount: "", Total: "", NetAmount: "" },
              { ItemName: " ", Qty: " ", Stock: "", MRP: " ", Amount: " ", Discount: "", Total: "", NetAmount: "" },
              { ItemName: " ", Qty: " ", Stock: "", MRP: " ", Amount: " ", Discount: "", Total: "", NetAmount: "" },
              { ItemName: "ItemName", Qty: "Qty", Stock: "", MRP: "ItemName", Amount: "Qty", Discount: "", Total: "ItemName", NetAmount: "Qty" },
               { ItemName: "Casual Shoes", Qty: 10, Stock: "", MRP: "Sandals & Floaters", Amount: 200, Discount: "", Total: "Running Shoes", NetAmount: 198 },
              { ItemName: "Sports Shoes", Qty: 20, Stock: "", MRP: "Flip- Flops", Amount: 600, Discount: "", Total: "Loafers", NetAmount: 570 },
              { ItemName: "Formal Shoes", Qty: 20, Stock: "", MRP: "Sneakers", Amount: 300, Discount: "", Total: "T-Shirts", NetAmount: 279 },
             
    ];

    window.fifaSchedule = [
                        { day: "Day", time: "Time", group: "Group", team: "Team", venue: "Venue", result: "Result" },
                        { day: "THURSDAY, JUNE 12, 2014", time: "20:00 GMT", group: "Group A", team: "Brazil vs  Croatia", venue: "Arena Corinthians", result: "3 - 1" },
                        { day: "FRIDAY, JUNE 13, 2014", time: "16:00 GMT", group: "Group A", team: "Mexico vs  Cameroon", venue: "Estadio das Dunas", result: "1 - 0" },
                        { day: "FRIDAY, JUNE 13, 2014", time: "19:00 GMT", group: "Group B", team: "Spain vs  Netherlands", venue: "Arena Fonte Nova", result: "1 -5" },
                        { day: "FRIDAY, JUNE 13, 2014", time: "22:00 GMT", group: "Group B", team: "Chile vs Australia", venue: "Arena Pantanal", result: "3 - 1" },
                        { day: "SATURDAY, JUNE 14, 2014", time: "16:00 GMT", group: "Group C", team: "Colombia vs Greece", venue: "Estadio Mineirao", result: "3 - 0" },
                        { day: "SATURDAY, JUNE 14, 2014", time: "19:00 GMT", group: "Group D", team: "Uruguay vs Costa Rica", venue: "Estadio Castelao", result: "1 - 3" },
                        { day: "SATURDAY, JUNE 14, 2014", time: "22:00 GMT", group: "Group D", team: "England vs Italy", venue: "Arena Amazonia", result: "1 - 2" },
                        { day: "SATURDAY, JUNE 14, 2014", time: "01:00 GMT", group: "Group C", team: "Ivory Coast vs Japan", venue: "Arena Pernambuco", result: "2 -1" },
                        { day: "SUNDAY, JUNE 15, 2014", time: "16:00 GMT", group: "Group E", team: "Switzerland vs Ecuador", venue: "Nacional", result: "2 - 1" },
                        { day: "SUNDAY, JUNE 15, 2014", time: "19:00 GMT", group: "Group E", team: "France vs Honduras", venue: "Estadio Beira-Rio", result: "3 - 0" },
                        { day: "SUNDAY, JUNE 15, 2014", time: "22:00 GMT", group: "Group F", team: "Argentina vs Bosnia ", venue: "Estadio do Maracana", result: "2 - 1" },
                        { day: "MONDAY, JUNE 16, 2014", time: "16:00 GMT", group: "Group G", team: "Germany vs Portugal", venue: "Arena Fonte Nova", result: "0 - 0" },
                        { day: "MONDAY, JUNE 16, 2014", time: "19:00 GMT", group: "Group F", team: "Iran vs Nigeria", venue: "Arena da Baixada", result: "4 - 0" },
                        { day: "MONDAY, JUNE 16, 2014", time: "22:00 GMT", group: "Group G", team: "Ghana vs United States", venue: "Estadio das Dunas", result: "1 - 2" },
                        { day: "TUESDAY, JUNE 17, 2014", time: "16:00 GMT", group: "Group H", team: "Belgium vs Algeria", venue: "Estadio Mineirao", result: "0 - 0" },
                        { day: "TUESDAY, JUNE 17, 2014", time: "19:00 GMT", group: "Group A", team: "Brazil vs Mexico", venue: "Estadio Castelao", result: "2 - 1" },
                        { day: "TUESDAY, JUNE 17, 2014", time: "22:00 GMT", group: "Group H", team: "Russia vs South Korea", venue: "Arena Pantanal", result: "1 - 1" },
                        { day: "WEDNESDAY, JUNE 18, 2014", time: "16:00 GMT", group: "Group B", team: "Australia vs Netherlands", venue: "Estadio Beira-Rio", result: "0 - 4" },
                        { day: "WEDNESDAY, JUNE 18, 2014", time: "19:00 GMT", group: "Group B", team: "Spain vs Chile", venue: "Estadio do Maracana", result: "2 - 3" },
                        { day: "WEDNESDAY, JUNE 18, 2014", time: "22:00 GMT", group: "Group A", team: "Cameroon vs Croatia", venue: "Arena Amazonia", result: "0 - 2" },
                        { day: "THURSDAY, JUNE 19, 2014", time: "16:00 GMT", group: "Group C", team: "Colombia vs Ivory Coast", venue: "Nacional", result: "2 - 1" },
                        { day: "THURSDAY, JUNE 19, 2014", time: "19:00 GMT", group: "Group D", team: "Uruguay vs England", venue: "Arena Corinthi", result: "0 - 0" },
                        { day: "THURSDAY, JUNE 19, 2014", time: "22:00 GMT", group: "Group C", team: "Japan vs Greece", venue: "Estadio das Dunas", result: "2 - 1" },
                        { day: "FRIDAY, JUNE 20, 2014", time: "16:00 GMT", group: "Group D", team: "Italy vs Costa Rica", venue: "Arena Pernambuco", result: "0 - 1" },
                        { day: "FRIDAY, JUNE 20, 2014", time: "19:00 GMT", group: "Group E", team: "Switzerland vs France", venue: "Arena Fonte Nova", result: "2 - 5" },
                        { day: "FRIDAY, JUNE 20, 2014", time: "22:00 GMT", group: "Group E", team: "Honduras vs Ecuador", venue: "Arena da Baixada", result: "1 - 2" },
                        { day: "SATURDAY, JUNE 21, 2014", time: "16:00 GMT", group: "Group F", team: "Argentina vs Iran", venue: "Estadio Mineirao", result: "1 - 0" },
                        { day: "SATURDAY, JUNE 21, 2014", time: "19:00 GMT", group: "Group G", team: "Germany vs Ghana", venue: "Estadio Castelao", result: "1 - 0" },
                        { day: "SATURDAY, JUNE 21, 2014", time: "22:00 GMT", group: "Group F", team: "Nigeria vs Bosnia", venue: "Arena Pantanal", result: "2 - 2" },
                        { day: "SUNDAY, JUNE 22, 2014", time: "16:00 GMT", group: "Group H", team: "Belgium vs Russia", venue: "Estadio Maracana", result: "2 - 2" },
                        { day: "SUNDAY, JUNE 22, 2014", time: "19:00 GMT", group: "Group H", team: "South Korea vs Algeria", venue: "Estadio Beira-Rio", result: "1 - 0" },
                        { day: "SUNDAY, JUNE 22, 2014", time: "20:00 GMT", group: "Group G", team: "United States vs Portugal", venue: "Arena Amazonia", result: "2 - 4" },
                        { day: "MONDAY, JUNE 23, 2014", time: "16:00 GMT", group: "Group B", team: "Australia vs Spain", venue: "Arena da Baixada", result: "1 - 4" },
                        { day: "MONDAY, JUNE 23, 2014", time: "16:00 GMT", group: "Group B", team: "Netherlands vs Chile", venue: "Arena Corinthians", result: "1 - 3" },
                        { day: "MONDAY, JUNE 23, 2014", time: "20:00 GMT", group: "Group A", team: "Croatia vs Mexico", venue: "Arena Pernambuco", result: "0 - 3" },
                        { day: "MONDAY, JUNE 23, 2014", time: "20:00 GMT", group: "Group A", team: "Cameroon vs Brazil", venue: "Estadio Nacional de Brasilia", result: "2 - 0" },
                        { day: "TUESDAY, JUNE 24, 2014", time: "16:00 GMT", group: "Group D", team: "Italy vs Uruguay", venue: "Estadio das Dunas", result: "2 - 1" },
                        { day: "TUESDAY, JUNE 24, 2014", time: "16:00 GMT", group: "Group D", team: "Costa Rica vs England", venue: "Estadio Mineirao", result: "1 - 4" },
                        { day: "TUESDAY, JUNE 24, 2014", time: "20:00 GMT", group: "Group C", team: "Japan vs Colombia", venue: "Arena Pantanal", result: "0 - 0" },
                        { day: "TUESDAY, JUNE 24, 2014", time: "20:00 GMT", group: "Group C", team: "Greece vs Ivory Coast", venue: "Estadio Castelao", result: "0 - 1" },
                        { day: "WEDNESDAY, JUNE 25, 2014", time: "16:00 GMT", group: "Group F", team: "Nigeria vs Argentina", venue: "Estadio Beira-Rio", result: "0 - 0" },
                        { day: "WEDNESDAY, JUNE 25, 2014", time: "16:00 GMT", group: "Group F", team: "Bosnia vs Iran", venue: "Arena Fonte", result: "0 - 3" },
                        { day: "WEDNESDAY, JUNE 25, 2014", time: "20:00 GMT", group: "Group E", team: "Honduras vs Switzerland", venue: "Arena Amazonia", result: "3 - 1" },
                        { day: "WEDNESDAY, JUNE 25, 2014", time: "20:00 GMT", group: "Group E", team: "Ecuador vs France", venue: "Estadio Maracana", result: "2 - 3" },
                        { day: "THURSDAY, JUNE 26, 2014", time: "16:00 GMT", group: "Group G", team: "United States vs Germany", venue: "Arena Pernambuc", result: "2 - 1" },
                        { day: "THURSDAY, JUNE 26, 2014", time: "16:00 GMT", group: "Group G", team: "Portugal vs Ghana", venue: "Estadio Nacional de Brasilia", result: "0 - 1" },
                        { day: "THURSDAY, JUNE 26, 2014", time: "20:00 GMT", group: "Group H", team: "South Korea vs Belgium", venue: "Arena Corinthians", result: "1 - 1" },
                        { day: "THURSDAY, JUNE 26, 2014", time: "20:00 GMT", group: "Group H", team: "Algeria vs Russia", venue: "Arena da Baixada", result: "0 - 1" },
                        { day: "SATURDAY, JUNE 28, 2014", time: "16:00 GMT", group: "", team: "Brazil vs Chile", venue: "Estadio Mineirao", result: "1(3) - 1(2)" },
                        { day: "SATURDAY, JUNE 28, 2014", time: "20:00 GMT", group: "", team: "Colombia vs Uruguay", venue: "Estadio do Maracana", result: "2 - 0" },
                        { day: "SUNDAY, JUNE 29, 2014", time: "16:00 GMT", group: "", team: "Netherlands vs Mexico", venue: "Estadio Castelao", result: "2 - 1" },
                        { day: "SUNDAY, JUNE 29, 2014", time: "20:00 GMT", group: "", team: "Costa Rica vs Greece", venue: "Arena Pernambuco", result: "1(5) - 1(3)" },
                        { day: "MONDAY, JUNE 30, 2014", time: "16:00 GMT", group: "", team: "France vs Nigeria", venue: "Nacional", result: "2 - 0" },
                        { day: "MONDAY, JUNE 30, 2014", time: "20:00 GMT", group: "", team: "Germany vs Algeria", venue: "Estadio Beira-Rio", result: "2 - 1" },
                        { day: "TUESDAY, JULY 1, 2014", time: "16:00 GMT", group: "", team: "Argentina vs Switzerland", venue: "Arena Corinthians", result: "1 - 0" },
                        { day: "TUESDAY, JULY 1, 2014", time: "20:00 GMT", group: "", team: "Belgium vs United States", venue: "Arena Fonte Nova", result: "2 - 1" },
                        { day: "FRIDAY, JULY 4, 2014", time: "16:00 GMT", group: "", team: "France vs Germany", venue: "Estadio dos Maracana", result: "0 - 1" },
                        { day: "FRIDAY, JULY 4, 2014", time: "20:00 GMT", group: "", team: "Brazil vs Colombia", venue: "Estadio Castelao", result: "2 - 1" },
                        { day: "SATURDAY, JULY 5, 2014", time: "16:00 GMT", group: "", team: "Argentina vs Belgium", venue: "Nacional", result: "1 - 0" },
                        { day: "SATURDAY, JULY 5, 2014", time: "20:00 GMT", group: "", team: "Netherlands vs Costa Rica", venue: "Arena Fonte Nova", result: "0(4) - 0(3)" },
                        { day: "TUESDAY, JULY 8, 2014", time: "20:00 GMT", group: "", team: "Brazil vs Germany", venue: "Estadio Mineirao", result: "1 - 7" },
                        { day: "WEDNESDAY, JULY 9, 2014", time: "20:00 GMT", group: "", team: "Netherlands vs Argentina", venue: "Arena Corinthians", result: "0(2) - 0(4)" },
                        { day: "SATURDAY, JULY 12, 2014", time: "20:00 GMT", group: "", team: "Brazil vs Netherlands", venue: "Nacional", result: "0 - 3" },
                        { day: "SUNDAY, JULY 13, 2014", time: "19:00 GMT", group: "", team: "Germany vs Argentina", venue: "Estadio do Maracana", result: "1 - 0" }
    ];

    window.fifaMOM = [
                  { rank: "Rank", name: "Name", team: "Team", opponent: "Opponent", awards: "Awards" },
                  { rank: 1, name: "Lionel Messi", team: " Argentina", opponent: "Bosnia and Herzegovina (GM), Iran (GM), Nigeria (GM), Switzerland (R16)", awards: 4 },
                  { rank: 2, name: "Keylor Navas", team: " Costa Rica", opponent: "England (GM), Greece (R16), Netherlands (QF)", awards: 3 },
                  { rank: 2, name: "Arjen Robben", team: " Netherlands", opponent: "Australia (GM), Chile (GM), Brazil (TP)", awards: 3 },
                  { rank: 2, name: "James Rodríguez", team: " Colombia", opponent: "Greece (GM), Ivory Coast (GM), Uruguay (R16)", awards: 3 },
                  { rank: 5, name: "Karim Benzema", team: " France", opponent: "Honduras (GM), Switzerland (GM)", awards: 2 },
                  { rank: 5, name: "Mario Götze", team: " Germany", opponent: "Ghana (GM), Argentina (FI)", awards: 2 },
                  { rank: 5, name: "Tim Howard", team: " United States", opponent: "Portugal (GM), Belgium (R16)", awards: 2 },
                  { rank: 5, name: "Thomas Müller", team: " Germany", opponent: "Portugal (GM), United States (GM)", awards: 2 },
                  { rank: 5, name: "Neymar", team: " Brazil", opponent: "Croatia (GM), Cameroon (GM)", awards: 2 },
                  { rank: 5, name: "Guillermo Ochoa", team: " Mexico", opponent: "Brazil (GM), Netherlands (R16)", awards: 2 },
                  { rank: 5, name: "Xherdan Shaqiri", team: "  Switzerland", opponent: "Ecuador (GM), Honduras (GM)", awards: 2 },
                  { rank: 5, name: "Islam Slimani", team: " Algeria", opponent: "South Korea (GM), Russia (GM)", awards: 2 },
                  { rank: 13, name: "Mario Balotelli", team: " Italy", opponent: "England (GM)", awards: 1 },
                  { rank: 13, name: "Gianluigi Buffon", team: " Italy", opponent: "Uruguay (GM)", awards: 1 },
                  { rank: 13, name: "Joel Campbell", team: " Costa Rica", opponent: "Uruguay (GM)", awards: 1 },
                  { rank: 13, name: "Júlio César", team: " Brazil", opponent: "Chile (R16)", awards: 1 },
                  { rank: 13, name: "Kevin De Bruyne", team: " Belgium", opponent: "Algeria (GM)", awards: 1 },
                  { rank: 13, name: "Clint Dempsey", team: " United States", opponent: "Ghana (GM)", awards: 1 },
                  { rank: 13, name: "Cristiano Ronaldo", team: " Portugal", opponent: "Ghana (GM)", awards: 1 },
                  { rank: 13, name: "Alexander Domínguez", team: " Ecuador", opponent: "France (GM)", awards: 1 },
                  { rank: 13, name: "Edin Džeko", team: " Bosnia and Herzegovina", opponent: "Iran (GM)", awards: 1 },
                  { rank: 13, name: "Eden Hazard", team: " Belgium", opponent: "Russia (GM)", awards: 1 },
                  { rank: 13, name: "Gonzalo Higuaín", team: " Argentina", opponent: "Belgium (QF)", awards: 1 },
                  { rank: 13, name: "Keisuke Honda", team: " Japan", opponent: "Greece (GM)", awards: 1 },
                  { rank: 13, name: "Mats Hummels", team: " Germany", opponent: "France (QF)", awards: 1 },
                  { rank: 13, name: "Toni Kroos", team: " Germany", opponent: "Brazil (SF)", awards: 1 },
                  { rank: 13, name: "David Luiz", team: " Brazil", opponent: "Colombia (QF)", awards: 1 },
                  { rank: 13, name: "Raïs M'Bolhi", team: " Algeria", opponent: "Germany (R16)", awards: 1 },
                  { rank: 13, name: "Mario Mandžukić", team: " Croatia", opponent: "Cameroon (GM)", awards: 1 },
                  { rank: 13, name: "Rafael Márquez", team: " Mexico", opponent: "Croatia (GM)", awards: 1 },
                  { rank: 13, name: "Jackson Martínez", team: " Colombia", opponent: "Japan (GM)", awards: 1 },
                  { rank: 13, name: "John Obi Mikel", team: " Nigeria", opponent: "Iran (GM)", awards: 1 },
                  { rank: 13, name: "Peter Odemwingie", team: " Nigeria", opponent: "Bosnia and Herzegovina (GM)", awards: 1 },
                  { rank: 13, name: "Robin van Persie", team: " Netherlands", opponent: "Spain (GM)", awards: 1 },
                  { rank: 13, name: "Paul Pogba", team: " France", opponent: "Nigeria (R16)", awards: 1 },
                  { rank: 13, name: "Sergio Romero", team: " Argentina", opponent: "Netherlands (SF)", awards: 1 },
                  { rank: 13, name: "Bryan Ruiz", team: " Costa Rica", opponent: "Italy (GM)", awards: 1 },
                  { rank: 13, name: "Georgios Samaras", team: " Greece", opponent: "Ivory Coast (GM)", awards: 1 }
    ];
    window.fifaTopScorers = [
                  { rank: "Rank", player: "Player", goals: "Goals", team: "Team", assists: "Assists", mins: "Minutes" },
                  { rank: 1, player: "James Rodriguez", goals: 6, team: "Colambia", assists: 2, mins: 67 },
                  { rank: 2, player: "Thomas Muller", goals: 5, team: "Germany", assists: 3, mins: 136 },
                  { rank: 3, player: "Neymar", goals: 4, team: "Brazil", assists: 1, mins: 114 },
                  { rank: 4, player: "Lionel Messi", goals: 4, team: "Argentina", assists: 1, mins: 173 },
                  { rank: 5, player: "Robin van Persie", goals: 4, team: "Netherlands", assists: 0, mins: 137 },
                  { rank: 6, player: "Karim Benzema", goals: 3, team: "France", assists: 2, mins: 150 },
                  { rank: 7, player: "Andre Schurrle", goals: 3, team: "Germany", assists: 1, mins: 81 },
                  { rank: 8, player: "Arjen Robben", goals: 3, team: "Netherlands", assists: 1, mins: 230 },
                  { rank: 9, player: "Enner Valencia", goals: 3, team: "Ecuador", assists: 0, mins: 90 },
                  { rank: 10, player: "Xherdan Shaqiri", goals: 3, team: "Switzerland", assists: 0, mins: 129 },
                  { rank: 11, player: "Toni Kroos", goals: 2, team: "Germany", assists: 3, mins: 345 },
                  { rank: 12, player: "Oscar", goals: 2, team: "Brazil", assists: 2, mins: 320 },
                  { rank: 13, player: "Abdelmoumene", goals: 2, team: "Algeria", assists: 1, mins: 85 },
                  { rank: 14, player: "Memphis Depay", goals: 2, team: "Netherlands", assists: 1, mins: 88 },
                  { rank: 15, player: "Ivan Perisic", goals: 2, team: "Croatia", assists: 1, mins: 129 },
    ];

    window.fifaTeamPlaces = [
                     { pos: "Position", team: "Team", g: "G", pld: "Pld", w: "W", d: "D", l: "L", pts: "Pts", gf: "GF", ga: "GA", gd: "GD" },
                     { pos: 1, team: "Germany", g: "G", pld: 7, w: 6, d: 1, l: 0, pts: 19, gf: 18, ga: 4, gd: 14 },
                     { pos: 2, team: "Argentina", g: "F", pld: 7, w: 5, d: 1, l: 1, pts: 16, gf: 8, ga: 4, gd: 4 },
                     { pos: 3, team: "Netherlands", g: "B", pld: 7, w: 5, d: 2, l: 0, pts: 17, gf: 15, ga: 4, gd: 11 },
                     { pos: 4, team: "Brazil", g: "A", pld: 7, w: 3, d: 2, l: 2, pts: 11, gf: 11, ga: 14, gd: -3 },
                     { pos: 5, team: "Colombia", g: "C", pld: 5, w: 4, d: 0, l: 1, pts: 12, gf: 12, ga: 4, gd: 8 },
                     { pos: 6, team: "Belgium", g: "H", pld: 5, w: 4, d: 0, l: 1, pts: 12, gf: 6, ga: 3, gd: 3 },
                     { pos: 7, team: "France", g: "E", pld: 5, w: 3, d: 1, l: 1, pts: 10, gf: 10, ga: 3, gd: 7 },
                     { pos: 8, team: "Costa Rica", g: "D", pld: 5, w: 2, d: 3, l: 0, pts: 9, gf: 5, ga: 2, gd: 3 },
                     { pos: 9, team: "Chile", g: "B", pld: 4, w: 2, d: 1, l: 1, pts: 7, gf: 6, ga: 4, gd: 2 },
                     { pos: 10, team: "Mexico", g: "A", pld: 4, w: 2, d: 1, l: 1, pts: 7, gf: 5, ga: 3, gd: 2 },
                     { pos: 11, team: "Switzerland", g: "E", pld: 4, w: 2, d: 0, l: 2, pts: 6, gf: 7, ga: 7, gd: 0 },
                     { pos: 12, team: "Uruguay", g: "D", pld: 4, w: 2, d: 0, l: 2, pts: 6, gf: 4, ga: 6, gd: -2 },
                     { pos: 13, team: "Greece", g: "C", pld: 4, w: 1, d: 2, l: 1, pts: 5, gf: 3, ga: 5, gd: -2 },
                     { pos: 14, team: "Algeria", g: "H", pld: 4, w: 1, d: 1, l: 2, pts: 4, gf: 7, ga: 7, gd: 0 },
                     { pos: 15, team: "United States", g: "G", pld: 4, w: 1, d: 1, l: 2, pts: 4, gf: 5, ga: 6, gd: -1 },
                     { pos: 16, team: "Nigeria", g: "F", pld: 4, w: 1, d: 1, l: 2, pts: 4, gf: 3, ga: 5, gd: -2 },
                     { pos: 17, team: "Ecuador", g: "E", pld: 3, w: 1, d: 1, l: 1, pts: 4, gf: 3, ga: 3, gd: 0 },
                     { pos: 18, team: "Portugal", g: "G", pld: 3, w: 1, d: 1, l: 1, pts: 4, gf: 4, ga: 7, gd: -3 },
                     { pos: 19, team: "Croatia", g: "A", pld: 3, w: 1, d: 0, l: 2, pts: 3, gf: 6, ga: 6, gd: 0 },
                     { pos: 20, team: "Bosnia", g: "F", pld: 3, w: 1, d: 0, l: 2, pts: 3, gf: 4, ga: 4, gd: 0 },
                     { pos: 21, team: "Ivory Coast", g: "C", pld: 3, w: 1, d: 0, l: 2, pts: 3, gf: 4, ga: 5, gd: -1 },
                     { pos: 22, team: "Italy", g: "D", pld: 3, w: 1, d: 0, l: 2, pts: 3, gf: 2, ga: 3, gd: -1 },
                     { pos: 23, team: "Spain", g: "B", pld: 3, w: 1, d: 0, l: 2, pts: 3, gf: 4, ga: 7, gd: -3 },
                     { pos: 24, team: "Russia", g: "H", pld: 3, w: 0, d: 2, l: 1, pts: 2, gf: 2, ga: 3, gd: -1 },
                     { pos: 25, team: "Ghana", g: "G", pld: 3, w: 0, d: 1, l: 2, pts: 1, gf: 4, ga: 6, gd: -2 },
                     { pos: 26, team: "England", g: "D", pld: 3, w: 0, d: 1, l: 2, pts: 1, gf: 2, ga: 4, gd: -2 },
                     { pos: 27, team: "South Korea", g: "H", pld: 3, w: 0, d: 1, l: 2, pts: 1, gf: 3, ga: 6, gd: -3 },
                     { pos: 28, team: "Iran", g: "F", pld: 3, w: 0, d: 1, l: 2, pts: 1, gf: 1, ga: 4, gd: -3 },
                     { pos: 29, team: "Japan", g: "C", pld: 3, w: 0, d: 1, l: 2, pts: 1, gf: 2, ga: 6, gd: -4 },
                     { pos: 30, team: "Australia", g: "B", pld: 3, w: 0, d: 0, l: 3, pts: 0, gf: 3, ga: 9, gd: -6 },
                     { pos: 31, team: "Honduras", g: "E", pld: 3, w: 0, d: 0, l: 3, pts: 0, gf: 1, ga: 8, gd: -7 },
                     { pos: 32, team: "Cameroon", g: "A", pld: 3, w: 0, d: 0, l: 3, pts: 0, gf: 1, ga: 9, gd: -8 }
    ];

function actionBegin(args) {
            if (args.reqType === "gotoSheet" && !args.newSheet) {
                var charts, len, i = 0, xlObj = $("#Spreadsheet").data("ejSpreadsheet");
                charts = xlObj.getSheetElement(args.gotoIndex).find(".e-datavisualization-chart");
                len = charts.length;
                while (i < len) {
                    $(charts[i]).ejChart("redraw");
                    i++;
                }
            }
}

function openfailure(args) {
	var xlObj = $("#Spreadsheet").data("ejSpreadsheet"), alertDlg = $("#" + xlObj._id + "_alertdlg");
	xlObj._renderAlertDlgContent(alertDlg, "Alert", args.statusText);
    alertDlg.ejDialog("open");
}